### PR TITLE
Prefab ays start

### LINKED ISSUE #348: j.tools.prefab.local.apps.atyourservice.start() fails 9.2.0
#### Installation information

- jumpscale version: 9.2
- operating system: Docker containers > ZInstall_ays9

#### Detailed description

`j.tools.prefab.local.apps.atyourservice.start()` should install the app if not done yet, instead of failing.

#### Steps to reproduce

screen shot 2017-10-24 at 15 43 51

#### Relevant stacktraces

```bash
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 j.tools.prefab.local.apps.atyourservice.start()

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/apps/PrefabAtYourService.py in start(self, host, port)
     61     def start(self, host='localhost', port=5000):
     62         cmd = 'cd {base_dir}; python3 main.py -h {host} -p {port}'.format(base_dir=self.base_dir, host=host, port=port)
---> 63         self.prefab.processmanager.ensure(name='atyourservice', cmd=cmd)
     64
     65     def stop(self):

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabProcessManager.py in ensure(self, name, cmd, env, path, descr, autostart, wait, expect)
    315                 if wait:
    316                     self.prefab.core.file_write(self.startupfile, 'sleep %s' % wait, append=True)
--> 317         self.prefab.tmux.executeInScreen("main", name, cmd, wait=wait, expect=expect)
    318
    319     def stop(self, name):

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabTmux.py in executeInScreen(self, sessionname, screenname, cmd, wait, cwd, env, user, tmuxuser, reset, replaceArgs, resetAfter, die, expect)
    167         if rc == 0:
    168             # we want to check to see if command really executed
--> 169             rc, out = checkOutput()
    170
    171         if resetAfter:

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabTmux.py in checkOutput()
    156                     msg += "Out/Err:\n%s\n" % out
    157                     if die:
--> 158                         raise j.exceptions.RuntimeError(msg)
    159                     else:
    160                         return 1, msg

RuntimeError: ERROR: Could not execute cmd:cd /opt/jumpscale9/app/atyourservice; python3 main.py -h localhost -p 5000
Out/Err:
**START**
-bash: cd: /opt/jumpscale9/app/atyourservice: No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory

root@js9:~#

 ((type:runtime.error)

In [4]: exit
```

### PR DESCRIPTION
**Pull request by abdulrahmantkhalifa**
#### What this PR resolves:
resolves #348

#### Changes proposed in this PR:

- the ays start now uses the prefab to be more consistent and reduce duplicate code
- requires https://github.com/Jumpscale/prefab9/pull/59 !!

**Version**: 

**Fixes**: #

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -1,2 +1,2 @@
 #for development mode
-pip3 install -e .
+js9 'j.tools.prefab.local.apps.atyourservice.install()'
```
Comment (zaibon) [inline install.sh]: Why can't we use pip to install Ays anymore?

Comment (abdulrahmantkhalifa) [reply install.sh]: @alichaddad  told me to move that to the prefab the original PR was just adding the prefab configs to the post install of the setup.Py, but ali makes sense cause this makes it more consistent with all the other repos using bash install to install right ?

Comment (abdulrahmantkhalifa) [reply install.sh]: and will also allow the curl install method so u only need the bash script to get the repo and install ays

Comment (zaibon) [reply install.sh]: @rkhamis any comment on this? I don't understand how we are supposed to make js9 pip installable if we keep using bash instead of pip everywhere.

Comment (abdulrahmantkhalifa) [reply install.sh]: i prefer the pip thing but if we are going to do that we have to be consistent in all the repos ,  and honestly just remove bash.install all together we can use the pre and post install of setup instead, but its up to u.

Comment (rkhamis) [reply install.sh]: My only point is to have the ays app installed. If you want to move that logic into the setup.py post install, that's fine.
